management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
server:
  port: 8443
  http2:
    enabled: true
  ssl:
    key-store: /opt/message-receiver-api.p12
    key-store-password: message-receiver-api
    key-store-type: pkcs12
    key-alias: message-receiver-api
    key-password: message-receiver-api
spring:
  jpa:
    hibernate:
      ddl-auto: update # WILL BE REMOVED WHEN LIQUIBASE IS RUNNING
    show-sql: true
  application:
    name: "message-receiver-api"

  datasource:
    url: jdbc:postgresql://localhost:5432/message-receiver-api
    username: postgres
    password: postgres

chat:
  exchanges:
    input: "user-events"
    old-messages: "old-message-requests"
    output: "incoming-messages"
    reprocess-messages: "reprocess-messages"
  file-api: "http://localhost:8080"
  private-key: "/opt/message-receiver-api.key"
  public-key: "/opt/message-receiver-api.crt"

firebase:
  bucket-name: tmdad-chat-app.appspot.com
  service-account: ./tmdad-chat-app-firebase-adminsdk.json