management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

spring:
  jpa:
    hibernate:
      ddl-auto: update # WILL BE REMOVED WHEN LIQUIBASE IS RUNNING
    show-sql: true
  application:
    name: "message-receiver-api"

  datasource:
    url: jdbc:postgresql://localhost:5432/message-receiver-api
    username: postgres
    password: postgres

chat:
  exchanges:
    input: "user-events"
    old-messages: "old-message-requests"
    output: "incoming-messages"
    reprocess-messages: "reprocess-messages"
  file-api: "http://localhost:8080"